export const CHANGE_SEARCH_FIELD: string = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING: string = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS: string = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED: string = 'REQUEST_ROBOTS_FAILED';

export const FILTER_ROBOTS: string = 'FILTER_ROBOTS';

export const CHANGE_CLICKME_COUNTER: string = 'INCREMENT_CLICKME_COUNTER';
